First iteration
Ararat25/go_final_project pull request #1
Opened 2024-08-05 22:34 UTC by Ararat25

2024-08-06 17:38 UTC, dirtymew requested changes
Привет Арарат

отличная работа:
 - логирование
 - документация
 - make
 - лайаут проекта(тут есть вопросы но в целом хорошо)

дал комментарии что улучшить и поправить - вот мб поможет по архитектуре 
https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10


вопрос задания со звездочками доделывать будешь?

2024-08-06 17:38 UTC, dirtymew commented on controller/addTask.go
> +	w.Write(respBytes)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-08-06 17:38 UTC, dirtymew commented on controller/addTask.go
> +		log.Println(err)
хмм так лог log.Println(error) теряется

2024-08-06 17:38 UTC, dirtymew commented on controller/doneTask.go
> +	task, err := h.service.DB.GetTaskById(idInt)
тут подробнее дам комментарий в сервисе

см проще бы было вызывать методы сервиса - так связность компонент ниже

те хендлеры ничего не знают про устройства сервсиса и что там есть сторадж

h.service.GetTask(id)

2024-08-06 17:38 UTC, dirtymew commented on controller/doneTask.go
> +	task, err := h.service.DB.GetTaskById(idInt)
ну и сервис мог бы реализовывать всю работу - те h.service.TaskDone(id)

2024-08-06 17:38 UTC, dirtymew commented on controller/signIn.go
> +	"github.com/Ararat25/go_final_project/customError"
что -то с импортами во всему проекту - нужно исправить

они должны быть сгруппированны и отсортированны

используй go imports

2024-08-06 17:38 UTC, dirtymew commented on controller/signIn.go
> +	envPassword := os.Getenv("TODO_PASSWORD")
это не очень хорошо - на каждый запрос ходить к os это дорого

все переменные окружения при старте нужно один раз считать

2024-08-06 17:38 UTC, dirtymew commented on customError/errors.go
> +package customError
просто errors  вместо  customError

2024-08-06 17:38 UTC, dirtymew commented on dbManager/scheduler.go
> +type Task struct {
ну раз у тебя есть пакет model то структуры лучше там все держать

2024-08-06 17:38 UTC, dirtymew commented on dbManager/scheduler.go
> +func (db *SchedulerStore) GetTasksByDate(limit int, date string) ([]Task, error) {
лимит у нас никак не меняется поэтому я бы его просто в константе бы обьявил

2024-08-06 17:38 UTC, dirtymew commented on dbManager/scheduler.go
> +func (db *SchedulerStore) EditTaskById(task *Task) error {
совет: 
 - я бы упростил интерфейс стораджа до стандартный CRUD методов
 - завел бы интерфес для абсракции

2024-08-06 17:38 UTC, dirtymew commented on model/repetitionRule.go
> +var timeLayout = "20060102" // шаблон для даты
в нескольких пакетах одна константа 

лучше сделать в однои

и вот это все про даты я бы вынес в пакет date - так как к моделям это отношение не имеет

2024-08-06 17:38 UTC, dirtymew commented on model/service.go
> +type Service struct {
это тоже не модель - лучше положить в отдельный пакет или

сделать один пакет task и там положить и структуру и сервис и сторадж...

2024-08-06 17:38 UTC, dirtymew commented on model/service.go
> +		DB:        db,
тут не стоит дб делать экспортируемой 

пусть с сервисом все общаются через его методы

2024-08-06 17:38 UTC, dirtymew commented on model/service.go
> +func (s *Service) VerifyUser(envPassword, password string) (string, error) {
стоит расширить интерфейс сервиса и сделать методы работы с задачами

addTask, getTask, FindTasks, Delete, Done итд 

а уже они будут вызывать внутри методы стораджа и валидировать задачи итд

2024-08-06 18:03 UTC, Ararat25 commented
@dirtymew
Здравствуйте, вообще хотелось бы доделать оставшиеся задания со звездочкой

2024-08-06 18:24 UTC, dirtymew commented
> @dirtymew
> 
> Здравствуйте, вообще хотелось бы доделать оставшиеся задания со звездочкой

Тогда стоит это сделать - после того как работа будет принята, на ревью уже повторно отправить не получится

2024-08-08 16:43 UTC, dirtymew requested changes
Привет Арарат

дал комментарии - есть пару критичных

2024-08-08 16:43 UTC, dirtymew commented on Dockerfile
> +
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это лучше в ENV или .env(если compose)

2024-08-08 16:43 UTC, dirtymew commented on Dockerfile
> +EXPOSE 8080/tcp
вроде другой порт по умолчанию в задании - и что будет если TODO_PORT поменяется

2024-08-08 16:43 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu:latest
лучше что-то полегче типа alpine взять

2024-08-08 16:43 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22.4-alpine AS builder
1.22.4 лучше туже версию что в go.mod

2024-08-08 16:43 UTC, dirtymew commented on controller/addTask.go
> +	_, _ = w.Write(respBytes)
ну раз логгер есть то и логировать ошибку стоит )

2024-08-08 16:43 UTC, dirtymew commented on task/dbManager/scheduler.go
> +	appPath, err := os.Executable()
лучше сделать так чтобы поумолчанию в папке проекта бд создавалась

2024-08-08 16:43 UTC, dirtymew commented on task/storage.go
> +	GetTasks() ([]entity.Task, error)
совет

можно из трех методов сделать один - Find(filter string)

2024-08-08 16:43 UTC, dirtymew commented on task/dbManager/scheduler.go
> +var dbPath = tests.DBFile
вот это прям очень плохо

ты на тесты завязался - так ни в коем случае делать нельзя @Ararat25

2024-08-08 16:43 UTC, dirtymew commented on middleware/auth.go
> +func (m Middleware) Auth(next http.Handler) http.Handler {
кажется ты отрезал страницу логина фронта 

фронтенд недоступен 

и тест падает - критично нужно исправить

2024-08-12 20:46 UTC, Ararat25 commented on middleware/auth.go
> +func (m Middleware) Auth(next http.Handler) http.Handler {
Вот этот момент так и не удалось воспроизвести

2024-08-14 11:55 UTC, dirtymew approved these changes
Привет Арарат

задание считаю выполненным

Поздравляю

2024-08-14 11:55 UTC, dirtymew commented on Makefile
> +start: build run
сходу не работает

<img width="605" alt="image" src="https://github.com/user-attachments/assets/0a633582-5307-4dcb-89e4-e0afb84160e0">

2024-08-14 11:55 UTC, dirtymew commented on Makefile
> +start: build run
ну и 404 у меня была по тем же причинам - внутри все повязано на пусти вида ../.

2024-10-14 19:29 UTC, merged